### PR TITLE
replace dataTableOutput with DT Output; remove lateness cols from dat…

### PR DESCRIPTION
**Pull request by andrewpbray**
…atable

### CODE REVIEW

**Comment by andrewpbray** [comment]
This removes all columns with lateness from the data table. This is in part to fix a bug that happens when we were calling the `round()` function on the `Total Lateness` col, which was a character vector. This is also in part to simplify the dashboard: there are already a lot of cols in this data table, so here at the outset, best to show a simpler version. We can always visit this datatable and allow the user to toggle which columns they'd like to see.

**Comment by andrewpbray** [comment]
@ryanlovett in terms of testing, what would happen if I clicked an nbgitpuller link tied to this branch? Would that allow me to test this branch on datahub? This is a case where the image would have one version of the app, but then nbgitpuller would...overwrite it?

**Comment by ryanlovett** [comment]
@andrewpbray Yes, you can create an nbgitpuller link that checks out the app into your home directory on the gradebook hub. I would suggest that you use RStudio rather than Shiny to view the app since you can also do development. If you visit nbgitpuller.link you can see where to specify the branch name.

You are correct that nbgitpuller cannot specify the download location -- everything gets put in your home directory. So if you want to test multiple branches with nbgitpuller it wouldn't work. You don't have to use nbgitpuller though. You can just check out the repo from the command-line on the gradebook hub.

The link below checks out the `modifying_policy_format` branch of the app and opens RStudio. You'd need to navigate to the app's directory, open the app.R, and run it.
https://gradebook.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fgradebook-dev%2Fgradebook-app&urlpath=rstudio%2F&branch=modifying_policy_format

(I just did that and it told me that I needed to add the `gradebook` R library, which makes sense since the library is installed in the extra container. You can `install.packages` it from with RStudio, which also gives you the opportunity to install a specific development version of it. Yes, it feels like this whole approach can be optimized, but the basics are there.)

nbgitpuller would not overwrite the app in production on gradebook hub since that is baked into the `extraContainer`.

**Comment by andrewpbray** [comment]
Gotcha. Thanks for laying that out. That makes sense to me.

**Review by nikita-jaya — APPROVED** [review]
Looks good!

**Pull request merged**
